### ISSUE TITLE
Can not sign a normal transaction with getting error cross-origin

### ISSUE THREAD

**Issue by thdailong** [randlabs/myalgo-connect#71]
Currently I am working on a project called Sigma wallet. I have a input where user would paste the base64 format transaction and sign the multisig transaction.
Now I am heading on making multisig transaction work with myalgo. But I have test if I paste a normal transaction and sign that transaction using myalgo wallet. It appear that window would spinning till the end of the universe with errors:
`Uncaught (in promise) DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.
    at isRef (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1329:20)
    at Object.get (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:622:9)
    at Proxy.signTransaction (webpack-internal:///./node_modules/@randlabs/myalgo-connect/lib/main.js:378:29)
    at async Proxy.signTransaction (webpack-internal:///./node_modules/@algo-builder/web/build/lib/myalgowallet-mode.js:69:12)
    at async Proxy.sign (webpack-internal:///./node_modules/@vue/cli-plugin-typescript/node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/MsigUI.vue?vue&type=script&lang=ts:91:27)
` 
Link to my source code: https://github.com/scale-it/algobuilder-msig/blob/815ea0a93504e0d00fff38bc40f67915a4b4eb46/src/pages/MsigUI.vue#L169

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/24353881/180504530-9b43bfaa-e2d7-4d8b-b61d-f8c8ad4e4b6a.png">

Is there any way that I can fix this?

Edited: I can access the the window `myalgo wallet connect` like below
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/24353881/181193370-2cf0e89f-adb5-4ec6-8332-d34aa608b87d.png">

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/24353881/181193545-c4e9f5e0-a2b3-451e-bf11-d69efc462ad7.png">

I have try to enable vue.config.js like this but it still did not work
<img width="472" alt="image" src="https://user-images.githubusercontent.com/24353881/181193993-f89ada4e-0aa1-4965-afef-fdb4f172da20.png">

**Comment by thdailong** [comment]
making `https` also not help me to solve this issues

**Comment by thdailong** [comment]
Looking around for some similar issues like this. I have found this link: [Link](https://github.com/solana-labs/wallet-adapter/issues/125)
It related to the ref https://github.com/vuejs/core/blob/3ca83179d1a798f65e4e70215c511e2f1b64adb6/packages/reactivity/src/ref.ts#L65-L67

**Comment by Alex99y** [comment]
@M-Picco can you check this?

**Comment by thdailong** [comment]
I think I have fixed the issues by myself now.
It seems that myalgo struggle with vuejs and therefore, we need to use shallowref to containt myalgo object!
